feature/LeaveApplication
Kelv1nG/iskulapp-laravel pull request #22
Opened 2024-11-12 14:02 UTC by FredMadrona

🎫 Ticket

[Leave Application ](https://trello.com/c/Fn8bkj64/72-filament-leave-application)

📦 Packages

none

📝 Updates

CRUD functionality for Leave Application section admin panel

🧪 Testing Steps

login to admin panel and select Leave Application section
![image](https://github.com/user-attachments/assets/b8a4f95e-822a-4ce4-9f4e-f4e7a8489f26)

2024-11-12 14:29 UTC, ejempic requested changes

2024-11-12 14:29 UTC, ejempic commented on src/app/Models/LeaveApplication.php
> +        'leave_type',
leave type should be enum

2024-11-12 14:29 UTC, ejempic commented on src/app/Models/LeaveApplication.php
> +        'status',
general enum type int

2024-11-12 14:29 UTC, ejempic commented on src/database/seeders/LeaveApplicationSeeder.php
> +            'status' => 'Pending',
pag enum na 
```suggestion
            'status' => STATUS::PENDING,
```

2024-11-12 14:29 UTC, ejempic commented on src/database/seeders/LeaveApplicationSeeder.php
> +            'leave_type' => 'Vacation',
```suggestion
            'leave_type' => LEAVE_TYPE::VACATION,
```

2024-11-19 04:51 UTC, Kelv1nG commented on src/app/Enums/LeaveStatus.php
> +}
enum value should still be a string,

case PENDING = 'pending' etc

avoid using magic numbers

2024-11-19 04:52 UTC, Kelv1nG commented on src/app/Enums/LeaveType.php
> +}
enum value should still be a string,

case SICK_LEAVE = 'sick_leave' etc

avoid using magic numbers

2024-11-19 04:52 UTC, Kelv1nG commented on src/database/migrations/2024_11_12_131427_create_leave_applications_table.php
> +            $table->unsignedSmallInteger('leave_type');
can set as enum

2024-11-21 07:38 UTC, Kelv1nG commented on src/database/migrations/2024_11_12_131427_create_leave_applications_table.php
> +            $table->enum('leave_status', ['Pending', 'Approved', 'Rejected']);
use values of enum directly here

$table->enum('column_name', array_column(MyEnum::cases(), 'value'));

2024-11-30 10:30 UTC, merged