chore: data seeding for multiple schools
Kelv1nG/iskulapp-laravel pull request #26
Opened 2024-11-28 13:19 UTC by Kelv1nG

🎫 Ticket

chore: data seeding for multiple schools

📦 Packages

None

📝 Updates

add seeders to simulate multiple schools / teachers / students

**School**
count = 2
```
for each school:
    3 years with 2 sems ( 6 academic years )

    10 grade levels
        2 section per grade level
        6 subjects per grade level

        6 subjects allocated per section
        20 students per section
```

**Teacher**
count = 20 / school

above calc is based on:
    6 subjects * 10 grade level * 2 section  / ( 3 subjects * 2 section per teacher) = 120 / 6 = 20

```    
for each teacher:
    3 subjects assigned to 2 sections

    1 assessment per assessment type and assessment status
    2-3 questions per assessment         
```

**Student**
   count = 2400 / school
   
   above calc is  based on:
         10 grade levels * 2 sections * 20 students per section = 400
         400 fresh students * 3 years * 2 semester = 2400
```         
for each student:
   6 allocated subjects
   1 section assigned
        
    some  students dont have assessments submitted
    some  students have incomplete answered questions to assessments
   ```
🧪 Testing Steps
       N/A

2024-11-28 18:20 UTC, ejempic commented on src/app/Enums/DayOfWeek.php
> +<?php
We could use carbon but its okay

2024-11-28 18:35 UTC, ejempic requested changes

2024-11-28 18:35 UTC, ejempic commented on src/database/seeders/AssessmentQuestionAnswerKeySeeder.php
> +        $trueOrFalseQuestions = AssessmentQuestion::where('question_type', 'true_or_false')->get();
All are true

2024-11-28 18:35 UTC, ejempic commented on src/database/seeders/AssessmentQuestionAnswerKeySeeder.php
> +                    'is_correct' => true,
All are true

2024-11-29 04:59 UTC, Kelv1nG commented on src/database/seeders/AssessmentQuestionAnswerKeySeeder.php
> +        $trueOrFalseQuestions = AssessmentQuestion::where('question_type', 'true_or_false')->get();
answer field updated to be true or false

for true or false questions, i think only the correct answer should be saved in the answer key, as the incorrect answer is implied.

update: [7beab](https://github.com/Kelv1nG/iskulapp-laravel/pull/26/commits/7beab80808e1fb73c57458d4a8fbed90b1fc46c7)

2024-11-29 05:04 UTC, Kelv1nG commented on src/database/seeders/AssessmentQuestionAnswerKeySeeder.php
> +                    'is_correct' => true,
this is intended, as this corresponds to 3 acceptable answers based on student input

i.e 
question: 
    who is the current president of our country?


accepted answers:

short answer1: BBM!
short answer2: BBM
short answer3: Mahal na Presidenteng BongBong Marcos Jr.

2024-11-29 06:07 UTC, Kelv1nG commented on src/app/Enums/DayOfWeek.php
> +<?php
enum removed

2024-12-03 09:42 UTC, merged